// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjVC_BgHmmj0omjeGao8LOFQwOya8eOGE',
    appId: '1:415978308440:web:45d45e04eaa44e37a7db2d',
    messagingSenderId: '415978308440',
    projectId: 'flutterfirebase-7415d',
    authDomain: 'flutterfirebase-7415d.firebaseapp.com',
    storageBucket: 'flutterfirebase-7415d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18Z8SHWGwLkAgyxXOpQS2sul93UAezPk',
    appId: '1:415978308440:android:6219d9afbe7a3bc2a7db2d',
    messagingSenderId: '415978308440',
    projectId: 'flutterfirebase-7415d',
    storageBucket: 'flutterfirebase-7415d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxptS2YvHOeBNKQcf9DPDcmEE6Im8RkrU',
    appId: '1:415978308440:ios:630ed8b1af6e79d1a7db2d',
    messagingSenderId: '415978308440',
    projectId: 'flutterfirebase-7415d',
    storageBucket: 'flutterfirebase-7415d.appspot.com',
    iosBundleId: 'com.example.zapateria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxptS2YvHOeBNKQcf9DPDcmEE6Im8RkrU',
    appId: '1:415978308440:ios:630ed8b1af6e79d1a7db2d',
    messagingSenderId: '415978308440',
    projectId: 'flutterfirebase-7415d',
    storageBucket: 'flutterfirebase-7415d.appspot.com',
    iosBundleId: 'com.example.zapateria',
  );
}
